In [ ]:
import numpy as np

In [ ]:
a1 = np.array ([1,2,3])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2 = np.array ([[1.5,2,3],
                [3,4,6]])

In [ ]:
a2

array([[1, 2, 3],
       [3, 4, 6]])

In [ ]:
a3 = np.array ([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
a3 = np.array ([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
type(a3)

numpy.ndarray

In [ ]:
a2.shape

(2, 3)

In [ ]:
a1.shape

(3,)

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

In [ ]:


a4 = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[20,21,22],[23,24,25],[26,27,28]]
])


In [ ]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [ ]:
type(a4)

numpy.ndarray

In [ ]:
a4.shape

(3, 3, 3)

In [ ]:
a4.ndim

3

In [ ]:
a1.dtype

dtype('int64')

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a2

array([[1, 2, 3],
       [3, 4, 6]])

In [ ]:
a2.dtype

dtype('float64')

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a1.size


3

In [ ]:
a2.size

6

In [ ]:
a3.size

18

In [ ]:
a4.size

27

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame (a2)

In [ ]:
df

0    1    2
0  1.5  2.0  3.0
1  3.0  4.0  6.0

In [ ]:
a2

array([[1.5, 2. , 3. ],
       [3. , 4. , 6. ]])

In [ ]:
arr1 = np.array ([1,2,3])

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr_one = np.ones ((2,4))

In [ ]:
arr_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr_one.shape

(2, 4)

In [ ]:
arr_one.ndim

2

In [ ]:
arr_one.dtype

dtype('float64')

In [ ]:
arr_zero = np.zeros((3,6))

In [ ]:
arr_zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr_zero.dtype

dtype('float64')

In [ ]:
arr_arange = np.arange (0,20,2)

In [ ]:
arr_arange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr_arange = np.arange (1,30,4)

In [ ]:
arr_arange

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [ ]:
arr_arange.dtype

dtype('int64')

In [ ]:
arr_arange.shape

(8,)

In [ ]:
arr_random = np.random.randint(4,12, size =( 3,5))

In [ ]:
arr_random

array([[ 5,  8,  7, 11,  5],
       [ 4,  6,  4,  9,  4],
       [10,  4, 11,  8,  9]])

In [ ]:
arr_random2 = np.random.random((2,3))

In [ ]:
arr_random2

array([[0.26786262, 0.75613879, 0.99548733],
       [0.86595751, 0.78321462, 0.32010065]])

In [ ]:
arr_random.dtype

dtype('int64')

In [ ]:
arr_random3 = np.random.rand(2,3)

In [ ]:
arr_random3

array([[0.29027327, 0.48985849, 0.46838951],
       [0.69139537, 0.16551162, 0.74526406]])

In [ ]:
np.random.seed(70)
arr_random = np.random.randint(4,12, size =( 3,5))
arr_random

array([[10, 10,  6,  4,  8],
       [ 7,  4,  8,  9,  9],
       [10,  9,  8, 11,  4]])

In [ ]:
np.random.seed(70)
arr_random4 = np.random.rand(3,5)
arr_random4

array([[0.92748054, 0.87242629, 0.58463127, 0.90517017, 0.31683257],
       [0.1480081 , 0.8595341 , 0.43370097, 0.4935208 , 0.4525637 ],
       [0.36315467, 0.26228467, 0.59132837, 0.31001098, 0.04370465]])

In [ ]:
np.unique(arr_random)

array([ 4,  6,  7,  8,  9, 10, 11])

In [ ]:
arr_random

array([[10, 10,  6,  4,  8],
       [ 7,  4,  8,  9,  9],
       [10,  9,  8, 11,  4]])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a1[0]

1

In [ ]:
a1[1]

2

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3[:2,:2,:1]

array([[[ 1],
        [ 4]],

       [[10],
        [13]]])